#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

python customer_train.py     --ppi_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.actions.SHS27k.txt     --protein_seq_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.SHS27k.sequences.dictionary.csv     --pdb_dir $PROJECT_ROOT/data/raw_data/all_pdbs     --cache_dir $PROJECT_ROOT/data/cache1     --config $PROJECT_ROOT/configs/precomputed_config.json     --experiment_name mape_experiment --split_mode random > test2.log

python customer_train.py     --ppi_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.actions.SHS27k.txt     --protein_seq_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.SHS27k.sequences.dictionary.csv     --pdb_dir $PROJECT_ROOT/data/raw_data/all_pdbs     --cache_dir $PROJECT_ROOT/data/cache2     --config $PROJECT_ROOT/configs/default_config.json     --experiment_name mape_experiment --split_mode random > test1.log

python customer_train.py     --ppi_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.actions.SHS27k.txt     --protein_seq_file $PROJECT_ROOT/data/processed_data_SHS27k/protein.SHS27k.sequences.dictionary.csv     --pdb_dir $PROJECT_ROOT/data/raw_data/all_pdbs     --cache_dir $PROJECT_ROOT/data/cache3     --config $PROJECT_ROOT/configs/esm2_config.json     --experiment_name mape_experiment --split_mode random > test3.log

python -B "customer_train.py"         --ppi_file "$PROJECT_ROOT/data/processed_data/protein.actions.rice.txt"         --protein_seq_file "$PROJECT_ROOT/data/processed_data/protein.rice.sequences.dictionary.csv"         --pdb_dir "$PROJECT_ROOT/data/raw_data/all_pdbs"         --cache_dir "$PROJECT_ROOT/graphcache/data/cache/rice_esmc_300m_bfs"         --config "$PROJECT_ROOT/configs/precomputed_esmc_300m_rice.json"    --split_mode "bfs"         --experiment_name "rice_esmc_300m_bfs" --embedding_dir "$PROJECT_ROOT/embedding/esmc-300m-2024-12/rice" --balance_dataset --enable_protein_positive_split  > $PROJECT_ROOT/results/rice_esmc_300m_bfs/training.log

python -B "customer_train.py"         --ppi_file "$PROJECT_ROOT/data/processed_data_SHS27k/protein.actions.SHS27k.txt"         --protein_seq_file "$PROJECT_ROOT/data/processed_data_SHS27k/protein.SHS27k.sequences.dictionary.csv"         --pdb_dir "$PROJECT_ROOT/data/raw_data/all_pdbs"         --cache_dir "$PROJECT_ROOT/graphcache/data/cache/SHS27k_esmc_300m_new_model_bfs"         --config "$PROJECT_ROOT/configs/multi_encoder_example.json"         --encoding_type "precomputed"         --split_mode "bfs"         --experiment_name "SHS27k_esmc_300m_new_model_bfs" --embedding_dir "$PROJECT_ROOT/embedding/esmc-300m-2024-12/SHS27k"  > $PROJECT_ROOT/results/SHS27k_esmc_300m_new_model_bfs/training.log

python -B "customer_train.py"         --ppi_file "$PROJECT_ROOT/data/processed_data/protein.actions.SHS27k.txt"         --protein_seq_file "$PROJECT_ROOT/data/processed_data/protein.SHS27k.sequences.dictionary.csv"         --pdb_dir "$PROJECT_ROOT/data/raw_data/all_pdbs"         --cache_dir "$PROJECT_ROOT/graphcache/data/cache/SHS27k_esm2_3b_pep_random"         --config "$PROJECT_ROOT/configs/precomputed_esm2_3b_pep_shs27k.json"         --encoding_type "precomputed"         --split_mode "random"         --experiment_name "SHS27k_esm2_3b_pep_random" --embedding_dir "$PROJECT_ROOT/embedding/esm2_t36_3B_UR50D/SHS27k"  > $PROJECT_ROOT/results/SHS27k_esm2_3b_pep_random/training.log
